### ISSUE TITLE
PECL event .dll not working

### ISSUE THREAD

**Issue by HallofFamer** [gentoo/proxy-maintainers#20]
Well I tried different versions of PECL event(1.10.3, 1.11, 1.11.1) with my WAMP server, and none of them would work. All gave out error messages like this:

[13-Feb-2015 11:54:34 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'D:/Development/WAMP/bin/php/php5.5.12/ext/php_event.dll' - The specified module could not be found.
 in Unknown on line 0

The issue is that, I cannot just take the source file and compile for a .dll file. The commands do not have one such as configure --enable-event, so I cannot build my own .dll file. This is frustrating, is there a way to solve the problem? If a working .dll cannot be provided, at least make it possible for me to make my own php_event.dll file using command configure --enable-event?

**Comment by mrueg** [comment]
This repository is for co-working with proxied maintainers, please file a bug on https://bugs.gentoo.org

**Comment by HallofFamer** [comment]
umm how can I post this to bugs.gentoo.org when I do not find the PECL event package in a list of projects it maintains?

**Comment by mrueg** [comment]
I guess this is the package your issue is about?
equery m pecl-event
 * dev-php/pecl-event [gentoo]
Herd:        proxy-maintainers (proxy-maint@gentoo.org)
Maintainer:  rrosmanov@gmail.com (Ruslan Osmanov)
             Maintainer. Assign bugs to him
Upstream:    None specified
Homepage:    http://pecl.php.net/event
Location:    /var/lib/portage/tree/dev-php/pecl-event
Keywords:    1.7.8:0: 
Keywords:    1.8.0:0: ia64
Keywords:    1.11.1:0: amd64 x86 ~ia64
License:     PHP-3
Just file a bug Product Gentoo Linux, Component Applications.
The bug wranglers will take care of it and  assign it to the correct herd/maintainer.

**Comment by HallofFamer** [comment]
I see, thanks.
